name: Arc Runner Test
on:
  workflow_dispatch:
    inputs:
        commit_or_tag:
          description: 'Commit hash or tag'
          required: true
          default: 'latest'
          type: string

jobs:
  runner-check:
    name: Runner Check
    runs-on: arc-runner-set
    # runs-on: ubuntu-latest
    # environment:
    #  name: prod  # ìƒì„±í•œ í™˜ê²½ ì´ë¦„
    steps:
      - name: Check run echo
        run: echo "ğŸ‰ This job uses runner scale set runners!"